-- V1__init_schema.sql
-- Schéma initial PresenceKFOKAM - conforme au diagramme D2

CREATE TABLE promotion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    annee VARCHAR(20) NOT NULL
);

CREATE TABLE etudiant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    prenom VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    promotion_id BIGINT NOT NULL,
    CONSTRAINT fk_etudiant_promotion FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE TABLE session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(200) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    ouverture_at TIMESTAMP NOT NULL,
    expiration_at TIMESTAMP NOT NULL,
    cloture_at TIMESTAMP,
    cloturee BOOLEAN NOT NULL DEFAULT FALSE,
    promotion_id BIGINT NOT NULL,
    CONSTRAINT fk_session_promotion FOREIGN KEY (promotion_id) REFERENCES promotion(id)
);

CREATE TABLE presence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    date_heure TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(20) NOT NULL CHECK (source IN ('ETUDIANT', 'FORMATEUR')),
    CONSTRAINT fk_presence_session FOREIGN KEY (session_id) REFERENCES session(id),
    CONSTRAINT fk_presence_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    CONSTRAINT uk_presence_session_etudiant UNIQUE (session_id, etudiant_id)
);

CREATE TABLE exercice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    etudiant_id BIGINT NOT NULL,
    lien VARCHAR(500) NOT NULL,
    statut VARCHAR(30) NOT NULL DEFAULT 'DEPOSE' CHECK (statut IN ('DEPOSE', 'EN_ATTENTE_RELECTURE', 'RELU')),
    date_depot TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modif_lien TIMESTAMP,
    CONSTRAINT fk_exercice_session FOREIGN KEY (session_id) REFERENCES session(id),
    CONSTRAINT fk_exercice_etudiant FOREIGN KEY (etudiant_id) REFERENCES etudiant(id),
    CONSTRAINT uk_exercice_session_etudiant UNIQUE (session_id, etudiant_id)
);

CREATE TABLE relecture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id BIGINT NOT NULL UNIQUE,
    relecteur_id BIGINT NOT NULL,
    note INTEGER NOT NULL CHECK (note BETWEEN 0 AND 20),
    commentaire VARCHAR(2000) NOT NULL,
    date_soumission TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modification TIMESTAMP,
    CONSTRAINT fk_relecture_exercice FOREIGN KEY (exercice_id) REFERENCES exercice(id),
    CONSTRAINT fk_relecture_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant(id)
);

-- Index pour performances
CREATE INDEX idx_session_promotion ON session(promotion_id);
CREATE INDEX idx_session_code ON session(code);
CREATE INDEX idx_presence_session ON presence(session_id);
CREATE INDEX idx_presence_etudiant ON presence(etudiant_id);
CREATE INDEX idx_exercice_session ON exercice(session_id);
CREATE INDEX idx_exercice_etudiant ON exercice(etudiant_id);
CREATE INDEX idx_exercice_statut ON exercice(statut);
CREATE INDEX idx_relecture_relecteur ON relecture(relecteur_id);