-- V3__deux_relecteurs.sql
-- Migration pour supporter deux relecteurs par exercice + moyenne

-- 1. Supprimer l'unicité sur exercice_id (un seul relecteur par exercice)
-- H2 ne supporte pas DROP CONSTRAINT directement sur clé unique sans nom
-- On recrée la table

CREATE TABLE relecture_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercice_id BIGINT NOT NULL,
    relecteur_id BIGINT NOT NULL,
    note INTEGER NOT NULL CHECK (note BETWEEN 0 AND 20),
    commentaire VARCHAR(2000) NOT NULL,
    date_soumission TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modification TIMESTAMP,
    ordre_relecteur SMALLINT NOT NULL DEFAULT 1, -- 1 ou 2
    note_provisoire BOOLEAN NOT NULL DEFAULT FALSE, -- true si une seule des deux notes rendue
    CONSTRAINT fk_relecture_new_exercice FOREIGN KEY (exercice_id) REFERENCES exercice(id),
    CONSTRAINT fk_relecture_new_relecteur FOREIGN KEY (relecteur_id) REFERENCES etudiant(id),
    CONSTRAINT uk_relecture_exercice_ordre UNIQUE (exercice_id, ordre_relecteur)
);

-- Copier les données existantes (ordre_relecteur = 1, note_provisoire = true si pas de 2ème)
INSERT INTO relecture_new (id, exercice_id, relecteur_id, note, commentaire, date_soumission, date_modification, ordre_relecteur, note_provisoire)
SELECT id, exercice_id, relecteur_id, note, commentaire, date_soumission, date_modification, 1, TRUE
FROM relecture;

DROP TABLE relecture;
ALTER TABLE relecture_new RENAME TO relecture;

-- Index pour performances
CREATE INDEX idx_relecture_exercice_ordre ON relecture(exercice_id, ordre_relecteur);
CREATE INDEX idx_relecture_relecteur ON relecture(relecteur_id);